### PR TITLE
Book 40 - Tweaks - Bookstore

### PR DESCRIPTION
**Pull request by KarinaAllard**
Minor fixes made in bookstore.css, such as:

- A few typos in class names
- Removal of unused, redundant or conflicting code
- Centering the heading on the book grid
- Centering the content-wrapper
- Minor margin fixes on mobile view
- Add a new search icon image with contrast color, used on hover
- Add cart contrast color on hover

### CODE REVIEW

**Review by jenster123 — CHANGES_REQUESTED** [review]
Nice detail with the pop-up kind of hover effect, looks great!!

Only thing that I can think of that we might be missing on the product page is a "next page", "previous page" kind of buttons, depending on if we want 100+ books to be viewed all at once or 10-20 at a time 😁

I approve of the changes, but I’d like to hear more opinions on this before we merge, especially since we're nearing the end of the project.

**Comment by KarinaAllard** [comment]
> Nice detail with the pop-up kind of hover effect, looks great!!
> 
> Only thing that I can think of that we might be missing on the product page is a "next page", "previous page" kind of buttons, depending on if we want 100+ books to be viewed all at once or 10-20 at a time 😁
> 
> I approve of the changes, but I’d like to hear more opinions on this before we merge, especially since we're nearing the end of the project.

I understand, I feel like that depends on the API side of things, and might be something that is added through js if it is something we want to do? Right now the button would have no purpose since this is just a static placeholder.

**Review by ElinSabel — APPROVED** [review]
I think Jenny has a point, if there is time it would be nice. However it doesnt necessary need to work it could be more of a design thing. Since this also have to be connected to the API ( I think ).

**Comment by eaback** [comment]
Pagination can be very complicated and is best done from the api side. The. You connect that from the FE using buttons and a bit js. Would be cool, but would be tight getting that done this sprint. 

Nice story for next sprint

**Review by eaback — APPROVED** [review]
Looks great. Move to merge. 

Keen eye for detail.

**Review by jenster123 — APPROVED** [review]

**Pull request merged**
