### PR TITLE
Book 43 - product_view

### PR DESCRIPTION
**Pull request by KarinaAllard**
I tried to maintain the design according to how Isolde created her product_view page, but with minor changes such as:

- Cart button got some graphical changes
- Aligned elements in buy-container with flex to center them vertically
- In mobile view, the hamburger button unexpectedly inherited general button styling, fixed that.
- Centered the text in mobile view
- Hover effect on the cart button
- Additional image of Foxy on the left side, to maintain the playfulness of the rest of the website
- Fixed the quantity width and added a placeholder number

Example of the button/quantity field changes:
Before:
Screenshot 2024-12-18 at 11 09 25

After:
Screenshot 2024-12-18 at 11 14 12

### CODE REVIEW

**Comment by jenster123** [comment]
Missing some space next tp the cart icon when I view it in my browser? but only on desktop. On mobile the space is there.
Not sure if it's just an issue on my side

chrome_qzjBn9Fxqt

**Review by ElinSabel — APPROVED** [review]
Looks good!

**Comment by KarinaAllard** [comment]
> Missing some space next tp the cart icon when I view it in my browser? but only on desktop. On mobile the space is there. Not sure if it's just an issue on my side

Not sure, it looks like this for me. 
Screenshot 2024-12-18 at 15 48 39

**Comment by isolde-alt** [comment]
I see the same thing as Jennie on my desktop and mobile  - can it be changes made in style.css that effects this? The fox is only partial visible in desktop view, but pop ups in mobile view. 
image

**Review by eaback — APPROVED** [review]
Looks good! Merge away

**Comment by KarinaAllard** [comment]
> I see the same thing as Jennie on my desktop and mobile - can it be changes made in style.css that effects this? The fox is only partial visible in desktop view, but pop ups in mobile view. 

So this issue has to do with your resolution. I can add some media queries to make him invisible when your resolution is too low. On a bigger screen he shows up just fine but gets cropped when you scale down the resolution. 

I'll investigate the gap issue which does not show up for me which makes it trickier. I have checked several resolutions and different browsers without replicating the issue.

**Comment by KarinaAllard** [comment]
I have made some changes, since I cannot see the issue I would need the team members that actually experience the gap issue to take a look at this for me. Thanks! 

EDIT: I just did a rebase which rewrites the history which is why it looks like I made all the commits now. This branch is up to date with main, and now have the two changes I think could solve the issues we saw yesterday.

**Comment by eaback** [comment]
Looks good on my machine, let's merge.

**Pull request merged**
